[workspace]
members = [
    "day01",
    "day02",
    "day03",
    "day04",
    "day05"
]

resolver = "2"

[workspace.dependencies]
anyhow = "1.*"
aoc_util = { git = "https://github.com/jluszcz/AdventOfCode-rs" }
log = "*"
